[build]
  # No build process needed for static HTML5 game
  publish = "."

[dev]
  # For local development
  command = "python3 -m http.server 8000"

[[headers]]
  # Cache static assets for better performance
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Handle 404s by serving index.html
  from = "/*"
  to = "/index.html"
  status = 404
